config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users 
  get 'lead_generators', to: 'users#lead_generators'	

  resources :leads
  post 'change_lead_owner', to: 'leads#change_lead_owner' 

  resources :email_templates
  post 'send_email', to: 'email_templates#send_email'	
  get 'compose_email', to: 'email_templates#compose_email'  

  # Admin routes  
	namespace :admin do
  	  get 'list_users', to: "users#list_users"
  	  post 'assign_manager', to: "users#assign_manager"
	end

  # Chat history
  get 'chat_history', to: 'email_conversations#chat_history'  
  get 'scheduled_emails', to: 'email_conversations#scheduled_emails'  
  post 'add_notes', to: 'email_conversations#add_notes'  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_conversation.rb
class EmailConversation < ApplicationRecord
  
  has_many :notes  

  def self.save_email(params, user)
    is_sent = false; send_date = Date.today     
    if params[:send_date].present? && params[:send_date]["(1i)"].present? && params[:send_date]["(2i)"].present? && params[:send_date]["(3i)"].present?
      date = "#{params[:send_date]["(1i)"]}/#{params[:send_date]["(2i)"]}/#{params[:send_date]["(3i)"]}"
      send_date = Date.parse(date)
      unless send_date > Date.today
        UserMailer.send_email(params).deliver rescue nil  
        is_sent = true     
      end  
    else
      UserMailer.send_email(params).deliver rescue nil
      is_sent = true     
    end  	
  	EmailConversation.create(sender_id: user.id, receiver_id: params[:receiver_id], receiver_email: params[:receiver_email], subject: params[:subject], content: params[:content], smtp: params[:smtp], is_sent: is_sent, sent_date: send_date, created_at: Time.now)
  end	

end

app/models/email_template.rb
class EmailTemplate < ApplicationRecord
  
  # Default created templates
  def self.default_templates(user_id)
  	EmailTemplate.where("user_id is null OR user_id = #{user_id}")
  end	

end

app/models/lead.rb
class Lead < ApplicationRecord

  belongs_to :user


end

app/models/note.rb
class Note < ApplicationRecord

  belongs_to :email_conversation
  belongs_to :user

end

app/models/role.rb
class Role < ApplicationRecord

  has_many :users

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :assign_role
  belongs_to :role, optional: true
  has_many :leads
  has_many :notes
  has_many :user_lead_generators
  has_many :lead_generators, through: :user_lead_generators
  has_many :inverse_user_lead_generators, class_name: "UserLeadGenerator", foreign_key: "manager_id"
  has_many :inverse_lead_generators, through: :inverse_user_lead_generators, source: :user

  # Assign lead generator role if role id missing
  def assign_role
  	default_role = Role.where(name: 'LeadGenerator').last
 	  self.role_id =  default_role.id if self.role_id.blank? && default_role.present?			
  end	

  def is_lead_generator?
  	role.present? && role.name == 'LeadGenerator'
  end	

  def is_manager?
  	role.present? && role.name == 'Manager'
  end	

  def is_admin?
  	role.present? && role.name == 'Admin'
  end	

  # List of managers
  def self.managers
    where("role_id in(select id from roles where name = 'Manager')")
  end    
  

  # Existimg manager
  def my_manager
    UserLeadGenerator.where(lead_generator_id: id).last
  end  


end

app/models/user_lead_generator.rb
class UserLeadGenerator < ApplicationRecord

  belongs_to :user
  belongs_to :lead_generator, class_name: "User"

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < BaseAdminController

  # List of all users
  def list_users
  	@users = User.all
  end  	

  # Assign lead generator to manager
  def assign_manager
  	user = User.find(params[:user_id].to_i)
    manager = user.my_manager
  	if manager.blank?
	    UserLeadGenerator.create(user_id: params[:manager_id], lead_generator_id: user.id)		
    else
      manager.update_attributes(user_id: params[:manager_id])
    end		
  	redirect_to admin_list_users_path
  end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/base_admin_controller.rb
class BaseAdminController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin

  # Admin access
  def check_admin
  	unless current_user.is_admin?
  	  redirect_to root_path	
  	end 	
  end	

end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  before_action :authenticate_user!

  private 
  # Manager access
  def check_manager
  	unless current_user.is_manager?
      redirect_to root_path		
    end		
  end	

end

app/controllers/email_conversations_controller.rb
class EmailConversationsController < BaseController

  before_action :check_manager 

  # Chat history of lead
  def chat_history
  	@chat_history = EmailConversation.where(receiver_id: params[:lead_id], is_sent: true)
  end	

  # Chat history of lead
  def scheduled_emails
    @chat_history = EmailConversation.where("sender_id = #{current_user.id} AND sent_date is not null")
  end 

  # Add notes to chat history
  def add_notes
  	Note.create!(content: params[:body], user_id: params[:user_id], email_conversation_id: params[:email_conversation_id])
  	redirect_to chat_history_path(lead_id: params[:lead_id])
  end 
  
end	

app/controllers/email_templates_controller.rb
class EmailTemplatesController < BaseController
   
  before_action :check_manager 

  def index
  	@email_templates = EmailTemplate.default_templates(current_user.id)
  end	

  # Compose custom email before send
  def compose_email
  	@email_template = EmailTemplate.where(id: params[:id]).last
  	if @email_template.blank? || (@email_template.user_id.present? && @email_template.user_id != current_user.id)
  	  redirect_to root_path	
  	else
  	  @user_ids = current_user.lead_generators.collect(&:id) << current_user.id
    end 
  end	

  # Send email
  def send_email 
    EmailConversation.save_email(params, current_user)
    redirect_to email_templates_path
  end

  def new
  	@email_template = EmailTemplate.new
  end

  def create
  	EmailTemplate.create(email_template_params)
  	redirect_to email_templates_path
  end	

  private
  def email_template_params
  	params[:email_template][:user_id] = current_user.id
  	params.require(:email_template).permit(:subject, :content, :user_id)
  end	


end

app/controllers/leads_controller.rb
class LeadsController < BaseController

  def new
  	@lead = Lead.new
  end
  
  def create
  	Lead.create(lead_params)
  	redirect_to leads_path
  end	

  def index
    if params[:user_id].present?
      Lead
      @leads = Lead.where(user_id: params[:user_id])
    else
      @leads = current_user.leads
    end  
  end 

  # Manager can change the owner of the lead
  def change_lead_owner
    lead = Lead.where(id: params[:lead_id]).last
    if lead.present? && lead.user_id == current_user.id && current_user.is_manager?
      lead.update_attributes(user_id: params[:user_id])
    end  
    redirect_to leads_path
  end 

  private
  def lead_params
  	params[:lead][:user_id] = current_user.id
  	params.require(:lead).permit(:first_name, :last_name, :email, :email2, :phone_number, :phone_number2, :status, :comment, :about_me, :category, :company_url, :user_id)
  end	


end

app/controllers/users_controller.rb
class UsersController < BaseController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def lead_generators
    @lead_generators = current_user.lead_generators
  end  

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_templates_helper.rb
module EmailTemplatesHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/admin/users/list_users.html.erb
<style type="text/css">
	td{padding: 5px}
</style>

<h4>Users</h4>  
<table border="1">
<tr>
<td>Name</td>
<td>Email</td>
<td>Role</td>
<td>Assign Manager</td>
</tr>
<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.role.name rescue '' %></td>
    <% if user.is_lead_generator? %>
      <%= form_tag admin_assign_manager_path do %>
        <td>
         <% existing_manager = user.my_manager.present? ? user.my_manager.user_id : nil %>
         <%= select_tag 'manager_id', options_for_select(User.managers.map{|x| [x.name, x.id]}, existing_manager), include_blank: true%>     
         <%= hidden_field_tag 'user_id', user.id %>
         <%= submit_tag 'Assign' %>
        </td>     
        <% end %>  
    <% end %>  
  </tr>
<% end %>
</table>

app/views/email_conversations/chat_history.html.erb
<% @chat_history.each do |chat| %>
    <p><%= chat.content %></p>	
    <div style="margin-left: 10px">	
	  <% chat.notes.each do |note| %>
	    <p><%= note.content %> by <%= note.user.name rescue 'NA' %> on <%= note.created_at.strftime("at %I:%M%p") %></p>
	  <% end %>
    </div>
    <%= form_tag add_notes_path do %>
        <p>
         <%= text_field_tag 'body', nil %>
         <%= hidden_field_tag 'email_conversation_id', chat.id %>
         <%= hidden_field_tag 'user_id', current_user.id %>
         <%= hidden_field_tag 'lead_id', params[:lead_id] %>
         <%= submit_tag 'Add Note' %>
        </p>     
        <% end %>
<% end %>

app/views/email_conversations/scheduled_emails.html.erb
<table>
<tr>
  <th>Email</th>
  <th>Content</th>
  <th>Content</th>
  <th>Scheduled on</th>
</tr>
<% @chat_history.each do |chat| %>
  <% if chat.is_sent == false %>
  <tr>
    <td><%= Lead.find(chat.receiver_id).email rescue nil %></td>
    <td><%= chat.subject %></td>
    <td><%= chat.content %></td>
    <td><%= chat.sent_date.strftime("%D") %></td>
  </tr>
  <% end %>
<% end %>
</table>

app/views/email_templates/_form.html.erb
<div class="col-sm-4">
  <div class="form-group">
    <%= f.text_field :subject, placeholder: 'Subject', class: 'form-control', required: true %>
  </div>	
  <div class="form-group">
    <%= f.text_area :content, cols: 40, rows: 10, placeholder: 'Body', class: 'form-control', required: true %>
  </div>
  <div class="form-group">  
    <%= f.submit 'Save', class: 'btn' %>  
  </div>
 </div> 

app/views/email_templates/compose_email.html.erb
<%= form_tag send_email_path do %>
  Receiver:<br/>
  <%#= email_field_tag 'receiver', nil, required: true %>
  <%= select_tag 'receiver_id', options_for_select(Lead.where(user_id: @user_ids).map{|x| ["#{x.email}", x.id]}), required: true %>     	
  <br/><br/>
  SMTP method:<br/>
    <%= select_tag 'smtp', options_for_select(['Mailgun', 'Gmail', 'SendGrid']) %><br/><br/>
  Send on:<br/>
  <%= date_select 'send_date', '', {include_blank: true, start_year: Date.current.year} %>     	
  <br/><br/>
  Subject:<br/>
  <%= text_field_tag 'subject', @email_template.subject, required: true %><br/><br/>
  Body:<br/>
  <%= text_area_tag 'content', @email_template.content, cols: 45, rows: 10, required: true %><br/><br/>
  <%= submit_tag 'Send' %>
<% end %>

app/views/email_templates/index.html.erb
<%= link_to 'Add New Template', new_email_template_path %><br/><br/>
<%= link_to 'Schedule Templates', scheduled_emails_path %><br/><br/>
<table>
<tr>
  <th>Subject</th>
  <th>Content</th>
</tr>
<% @email_templates.each do |template| %>
  <tr>
    <td><%= template.subject %></td>
    <td><%= template.content %></td>
    <td><%= link_to 'Choose', compose_email_path(id: template.id) %></td>
  </tr>
<% end %>
</table>

app/views/email_templates/new.html.erb
<h4>Add New Lead</h4>
<%= form_for @email_template, url: email_templates_path do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/layouts/_left_nav_bar.erb
<div id="wrapper">
<%# Rails flash messages styled for Bootstrap 3.0 %>

    <!-- Sidebar -->
      <div id="sidebar-wrapper">
        <ul class="sidebar-nav">        
          <li>
            <a href="#">Dashboard</a>
          </li>
          <% if user_signed_in? %>
            <% unless current_user.is_admin? %>
              <li>
                <%= link_to 'Leads', leads_path %>  
              </li>       
            <% end %>  
            <% if current_user.is_manager? %>
              <li>
                <%= link_to 'LeadGenerators', lead_generators_path %>  
              </li> 
              <li>
                <%= link_to 'Email Templates', email_templates_path %>  
              </li> 
            <% end %>  
            <% if current_user.is_admin? %>
              <li>
                <%= link_to 'Users', admin_list_users_path %>  
              </li>               
            <% end %> 
          <% end %>  
        </ul>
      </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div>
                <% flash.each do |name, msg| %>
                    <% if msg.is_a?(String) %>
                      <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <%= content_tag :div, msg, :id => "flash_#{name}" %>
                      </div>
                    <% end %>
                  <% end %>
                   <!--  <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a> -->
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Menu Toggle Script -->
<script>
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
});
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

<div id="wrapper">

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <a href="#">
                    Start Bootstrap
                </a>
            </li>
            <li>
                <a href="#">Dashboard</a>
            </li>
            <li>
              <%= link_to 'Leads', new_lead_path %>  
            </li>       
        </ul>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div>
                   <!--  <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a> -->
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Menu Toggle Script -->
<script>
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
});
</script>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%#= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lead Management" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Lead Management" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <div id="wrapper">
       <%= render 'layouts/left_nav_bar' %>
       <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div>
              <%= yield %>
            </div>
          </div>
       </div>
    </main>
  </body>
</html>

app/views/leads/_form.html.erb
<div class="col-sm-4">
  <div class="form-group">
    <%= f.text_field :first_name, placeholder: 'First Name', class: 'form-control', required: true %>
  </div>	
  <div class="form-group">
    <%= f.text_field :last_name, placeholder: 'Last Name', class: 'form-control', required: true %>
  </div>
  <div class="form-group">  
    <%= f.email_field :email, placeholder: 'Email', class: 'form-control' %>
  </div>
  <div class="form-group">  
    <%= f.email_field :email2, placeholder: 'Email2', class: 'form-control' %>
  </div>
  <div class="form-group">  
    <%= f.text_field :phone_number, placeholder: 'Phone Number', class: 'form-control' %>
  </div>
  <div class="form-group">  
    <%= f.text_field :phone_number2, placeholder: 'Phone Number2', class: 'form-control' %>
  </div>
  <div class="form-group">  
    <%= f.text_field :category, placeholder: 'Category', class: 'form-control' %>
  </div>  
  <div class="form-group">  
    <%= f.text_field :company_url, placeholder: 'Company url', class: 'form-control' %>
  </div>  
  <div class="form-group">  
    <%= f.text_field :about_me, placeholder: 'About me', class: 'form-control' %>
  </div>  
  <div class="form-group">  
    <%= f.text_field :status, placeholder: 'Status', class: 'form-control' %>
  </div>  
  <div class="form-group">  
    <%= f.text_field :comment, placeholder: 'Comment', class: 'form-control' %>
  </div>
  <div class="form-group">  
    <%= f.submit 'Save', class: 'btn' %>  
  </div>
 </div> 

app/views/leads/index.html.erb
<style type="text/css">
	td{padding: 5px}
</style>

<h4>Leads</h4>
<%= link_to 'Add Lead', new_lead_path, style: 'float:right' %>  
<table border="1">
<tr>
<td>FirstName</td>
<td>LastName</td>
<td>Email</td>
<td>Email2</td>
<td>Phone</td>
<td>Phone2</td>
<td>Category</td>
<td>Company Url</td>
<td>Status</td>
<td>Comment</td>
<td>About me</td>
<% if current_user.is_manager? %>
  <td>Assign to manager</td>
  <td>Chat history</td>
<% end %>  
</tr>
<% @leads.each do |lead| %>
  <tr>
    <td><%= lead.first_name %></td>
    <td><%= lead.last_name %></td>
    <td><%= lead.email %></td>
    <td><%= lead.email2 %></td>
    <td><%= lead.phone_number %></td>
    <td><%= lead.phone_number2 %></td>
    <td><%= lead.category %></td>
    <td><%= lead.company_url %></td>
    <td><%= lead.status %></td>
    <td><%= lead.comment %></td>
    <td><%= lead.about_me %></td>
    <% if current_user.is_manager? %>
      <%= form_tag change_lead_owner_path do %>
        <td>    
         <%= select_tag 'user_id', options_for_select(User.managers.map{|x| [x.name, x.id]}, current_user.id), include_blank: true%>     
         <%= hidden_field_tag 'lead_id', lead.id %>
         <%= submit_tag 'Assign' %>
        </td>     
        <% end %>  
      <td>
        <%= link_to 'Chat History', chat_history_path(lead_id: lead.id) %>
      </td>  
    <% end %>  
  </tr>
<% end %>
</table>

app/views/leads/new.html.erb
<h4>Add New Lead</h4>
<%= form_for @lead, url: leads_path do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/lead_generators.html.erb
<style type="text/css">
    td{padding: 5px}
</style>

<h4>Users</h4>  
<table border="1">
<tr>
<td>Name</td>
<td>Email</td>
<td>Leads</td>
</tr>
<% @lead_generators.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Leads', leads_path(user_id: user.id) %></td>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
Welcome to the board!